name: Publish Docker image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/hurryhand
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:ultimo -t $IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/hurryhand
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:ultimo
          docker push $IMAGE_NAME:${{ github.sha }}